# -*- coding: utf-8 -*-
"""ai-project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QfG9Vcd346dA9iOqTc3TdmbYtjsMWp8o

**TITLE:Simple Ledge Balancer**

**Description:Develop a script that checks if debit and credit entries in a ledger balance correctly.**

**prompt:Develop a Python script named Simple Ledger Balancer that verifies whether debit and credit entries in a financial ledger are balanced.**

# Simple Ledger Balancer

## Description
This Python script provides a simple function to verify whether debit and credit entries in a financial ledger are balanced. It calculates the sum of all debit entries and all credit entries and determines if these sums are equal. The script also includes a set of test cases to demonstrate its functionality with various scenarios (balanced, unbalanced, and empty ledgers).

## Features
*   `check_ledger_balance` function to compare total debits and credits.
*   Includes multiple test cases to validate the function's accuracy.
*   Prints detailed output for each test case, showing debits, credits, totals, and balance status.

## Installation
No external libraries are required. This script uses standard Python built-in functions and data types.

## How to Run
1.  **Open in Google Colab:** If you are viewing this in a Google Colab notebook, simply run the code cell containing the `check_ledger_balance` function and its test cases.
2.  **Local Execution:** Copy the Python code into a `.py` file (e.g., `ledger_balancer.py`) and run it from your terminal using `python ledger_balancer.py`.

The script will automatically execute the defined test cases and print their results to the console.

## Code Explanation

### `check_ledger_balance(debits, credits)` function
*   **Purpose:** This function takes two lists, `debits` and `credits`, representing financial transactions, and checks if their sums are equal.
*   **Parameters:**
    *   `debits` (list of float or int): A list containing individual debit amounts.
    *   `credits` (list of float or int): A list containing individual credit amounts.
*   **Process:**
    1.  `total_debits = sum(debits)`: Calculates the sum of all elements in the `debits` list.
    2.  `total_credits = sum(credits)`: Calculates the sum of all elements in the `credits` list.
    3.  `is_balanced = (total_debits == total_credits)`: Compares the two sums. If they are equal, `is_balanced` will be `True`; otherwise, it will be `False`.
*   **Returns:** A tuple containing:
    *   `bool`: `True` if balanced, `False` otherwise.
    *   `float`: The total sum of debit entries.
    *   `float`: The total sum of credit entries.

### Test Cases
The script includes several test cases (`Test Case 1` through `Test Case 5`) to cover different scenarios:
*   **Balanced Ledger:** Debits and credits sum up to the same amount.
*   **Unbalanced Ledger (Debits > Credits):** Total debits are greater than total credits.
*   **Unbalanced Ledger (Credits > Debits):** Total credits are greater than total debits.
*   **Empty Entries:** Both debit and credit lists are empty (expected to be balanced as both sums are 0).
*   **Complex Scenario:** More realistic numbers for both debits and credits.

Each test case calls `check_ledger_balance` with specific inputs and then prints the inputs, calculated totals, and the `Is Balanced` status. `assert` statements are used to programmatically verify the correctness of the function's output against expected results.

## Sample Input and Expected Output

### Sample Input (from Test Case 1)
```python
debits_1 = [100.00, 50.00, 25.00]
credits_1 = [75.00, 100.00]
```

### Expected Output (for Sample Input above)
```
Test Case 1 (Balanced):
  Debits: [100.0, 50.0, 25.0] (Total: 175.00)
  Credits: [75.0, 100.0] (Total: 175.00)
  Is Balanced: True
```

### Another Sample Input (from Test Case 2)
```python
debits_2 = [200.00, 100.00]
credits_2 = [150.00, 50.00]
```

### Expected Output (for Another Sample Input above)
```
Test Case 2 (Unbalanced - Debits > Credits):
  Debits: [200.0, 100.0] (Total: 300.00)
  Credits: [150.0, 50.0] (Total: 200.00)
  Is Balanced: False
```

## Libraries Used
*   **Python Built-in Functions:** `sum()`, `print()`, `assert()`.

## Comments and Docstrings
The provided Python code includes:
*   A comprehensive docstring for the `check_ledger_balance` function, explaining its purpose, arguments, and return values.
*   Comments within the test cases section to clarify each test's intent and expected outcome.
"""

def check_ledger_balance(debits, credits):
    """
    Verifies whether debit and credit entries in a financial ledger are balanced.

    Args:
        debits (list of float or int): A list of debit amounts.
        credits (list of float or int): A list of credit amounts.

    Returns:
        bool: True if the ledger is balanced (total debits equals total credits), False otherwise.
        float: The total sum of debit entries.
        float: The total sum of credit entries.
    """
    total_debits = sum(debits)
    total_credits = sum(credits)

    is_balanced = (total_debits == total_credits)

    return is_balanced, total_debits, total_credits

# --- Test Cases and Sample Inputs ---
print("--- Simple Ledger Balancer Test Cases ---")

# Test Case 1: Balanced Ledger
debits_1 = [100.00, 50.00, 25.00]
credits_1 = [75.00, 100.00]
is_balanced_1, total_debits_1, total_credits_1 = check_ledger_balance(debits_1, credits_1)
print(f"\nTest Case 1 (Balanced):")
print(f"  Debits: {debits_1} (Total: {total_debits_1:.2f})")
print(f"  Credits: {credits_1} (Total: {total_credits_1:.2f})")
print(f"  Is Balanced: {is_balanced_1}")
assert is_balanced_1 == True, "Test Case 1 Failed: Should be balanced"

# Test Case 2: Unbalanced Ledger (Debits > Credits)
debits_2 = [200.00, 100.00]
credits_2 = [150.00, 50.00]
is_balanced_2, total_debits_2, total_credits_2 = check_ledger_balance(debits_2, credits_2)
print(f"\nTest Case 2 (Unbalanced - Debits > Credits):")
print(f"  Debits: {debits_2} (Total: {total_debits_2:.2f})")
print(f"  Credits: {credits_2} (Total: {total_credits_2:.2f})")
print(f"  Is Balanced: {is_balanced_2}")
assert is_balanced_2 == False, "Test Case 2 Failed: Should be unbalanced"

# Test Case 3: Unbalanced Ledger (Credits > Debits)
debits_3 = [50.00, 25.00]
credits_3 = [100.00, 5.00]
is_balanced_3, total_debits_3, total_credits_3 = check_ledger_balance(debits_3, credits_3)
print(f"\nTest Case 3 (Unbalanced - Credits > Debits):")
print(f"  Debits: {debits_3} (Total: {total_debits_3:.2f})")
print(f"  Credits: {credits_3} (Total: {total_credits_3:.2f})")
print(f"  Is Balanced: {is_balanced_3}")
assert is_balanced_3 == False, "Test Case 3 Failed: Should be unbalanced"

# Test Case 4: Empty Entries (Should be balanced)
debits_4 = []
credits_4 = []
is_balanced_4, total_debits_4, total_credits_4 = check_ledger_balance(debits_4, credits_4)
print(f"\nTest Case 4 (Empty Entries):")
print(f"  Debits: {debits_4} (Total: {total_debits_4:.2f})")
print(f"  Credits: {credits_4} (Total: {total_credits_4:.2f})")
print(f"  Is Balanced: {is_balanced_4}")
assert is_balanced_4 == True, "Test Case 4 Failed: Should be balanced"

# Test Case 5: Complex Scenario
debits_5 = [123.45, 67.89, 10.00, 4.56]
credits_5 = [100.00, 50.00, 55.90, 0.00]
is_balanced_5, total_debits_5, total_credits_5 = check_ledger_balance(debits_5, credits_5)
print(f"\nTest Case 5 (Complex Scenario):")
print(f"  Debits: {debits_5} (Total: {total_debits_5:.2f})")
print(f"  Credits: {credits_5} (Total: {total_credits_5:.2f})")
print(f"  Is Balanced: {is_balanced_5}")
# Manually check sum for expected outcome
expected_balance_5 = (sum(debits_5) == sum(credits_5))
assert is_balanced_5 == expected_balance_5, "Test Case 5 Failed: Mismatch in balance status"

print("\nAll test cases executed. Check outputs for balance status.")

"""**AI_TXT**
**Tool(s) used: This is a Google Colab AI Agent, leveraging internal orchestration and code generation capabilities.**

**Example prompt(s) you gave:
"Develop a Python script named Simple Ledger Balancer that verifies whether debit and credit entries in a financial ledger are balanced. the code should conduct test cases and sample inputs"
"and give me readme and explaining the code of each line and how command runs and sample input and expected output and the libraries used and comments docstrings"**

**"with in the code"**
**"give me the code as usual"**
**"where readme"**
**"give me ai_txt(shot template) ..."**

**How AI helped:**
**Code Generation: Generated the initial Python script (check_ledger_balance function and its test cases) based on the prompt.**

**Documentation Generation: Generated a comprehensive README in markdown format, explaining the script's purpose, features, installation, how to run, detailed code explanation, sample inputs/out88puts, libraries used, and comments/docstrings.**

**Code Integration: Modified an existing markdown cell to incorporate the generated README content directly into the notebook.**

**Clarification and Retrieval: Helped to clarify the location of the README content and retrieved the Python code upon request.**

**Any manual corrections you made: No manual corrections were made during this interaction.**


"""